#!/usr/bin/env bash
# Linux build script for Roaster Logger
# Requires pyinstaller installed in the active environment.
# Run with: bash scripts/build_linux.sh
set -e

# ensure default config/data exist so PyInstaller can bundle them
mkdir -p config data/logs
if [ ! -f config/settings.toml ]; then
cat > config/settings.toml <<'EOF'
# autogenerated settings
[app]
name = "roaster_logger"
env = "local"
log_dir = "data/logs"

[logging]
level = "INFO"
format = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
max_bytes = 1048576
backup_count = 5

ports = []
EOF
fi

pyinstaller --windowed --onefile \
  --name roaster_logger \
  --icon icon.png \
  --add-data "config:config" \
  --add-data "data:data" \
  ui/desktop/app.py

echo "Build finished. Output is under dist/roaster_logger"
